apiVersion: v1
kind: Service
metadata:
  name: nginx-github-service
  namespace: default  # or the appropriate namespace you want this service to be in
spec:
  type: NodePort
  selector:
    app: nginx-github
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31339

